// Generated by Dagger (https://dagger.dev).
package com.example.baseapplication.data.remote;

import com.example.baseapplication.data.ApiService;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class AuthRepository_Factory implements Factory<AuthRepository> {
  private final Provider<ApiService> apiServiceProvider;

  public AuthRepository_Factory(Provider<ApiService> apiServiceProvider) {
    this.apiServiceProvider = apiServiceProvider;
  }

  @Override
  public AuthRepository get() {
    return newInstance(apiServiceProvider.get());
  }

  public static AuthRepository_Factory create(Provider<ApiService> apiServiceProvider) {
    return new AuthRepository_Factory(apiServiceProvider);
  }

  public static AuthRepository newInstance(ApiService apiService) {
    return new AuthRepository(apiService);
  }
}
